version: '2'
services:
  zookeeper:
    build: .
    ports:
      - "8181:8181"
      - "3888:3888"
      - "2888:2888"
      - "2181:2181"
    environment:
      CLUSTER_SIZE: 1
      CONFIG_TYPE: file
      ZK_PASSWORD: mypassword
